env: "local" # Виды конфигов local, dev, prod
storage_path: "./storage/storage.sqlite3" # путь до DB
http_server:
  address: "localhost:8082"

  # таймаут, то есть время на чтение запроса от клиента
  # и такое же время на отправку ответа клиенту
  # время на обратботку запроса не ограничено.
  timeout: 4s 

  # время жизни соединения с клиентом
  # если один клиент много запрашивает - одно соединение реиспользуем
  # если он долго не использует соединение - обрываем через 60сек
  idle_timeout: 60s 

